export * from './header/header.component';
export * from './footer/footer.component';
export * from './cart/cart.component';
export * from './aside/aside.component';
export * from './slider/slider.component';
export * from './single-product/single-product.component';
export * from './list-product/list-product.component';
export * from './search/search.component';
export * from './user-aside/user-aside.component';
